CREATE TABLE "users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "role" varchar NOT NULL,
  "store_id" integer,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "user_profiles" (
  "profile_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer UNIQUE NOT NULL,
  "full_name" varchar NOT NULL,
  "avatar_media_id" integer,
  "phone_number" varchar,
  "bio" text
);

CREATE TABLE "stores" (
  "store_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" integer NOT NULL,
  "logo_media_id" integer,
  "store_name" varchar NOT NULL,
  "store_address" text,
  "store_description" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "media" (
  "media_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uploaded_by_user_id" integer NOT NULL,
  "file_path" varchar NOT NULL,
  "file_name" varchar,
  "mime_type" varchar,
  "file_size" integer,
  "alt_text" varchar,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "store_layouts" (
  "store_id" integer PRIMARY KEY,
  "head_title" varchar,
  "head_favicon_media_id" integer,
  "seo_meta_description" text,
  "seo_meta_keywords" text,
  "seo_og_title" varchar,
  "seo_og_description" text,
  "seo_og_image_media_id" integer,
  "structured_data_schema" json,
  "slider_content" json,
  "body_content" text,
  "purchase_guide_content" text,
  "footer_content" text,
  "updated_at" timestamp
);

CREATE TABLE "products" (
  "product_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "store_id" integer NOT NULL,
  "category_id" integer,
  "product_name" varchar NOT NULL,
  "product_description" text,
  "base_price" decimal(10,2) NOT NULL,
  "discount_price" decimal(10,2),
  "is_published" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "categories" (
  "category_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "store_id" integer NOT NULL,
  "category_name" varchar NOT NULL,
  "parent_category_id" integer
);

CREATE TABLE "product_variants" (
  "variant_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer NOT NULL,
  "variant_name" varchar NOT NULL,
  "variant_value" varchar NOT NULL,
  "additional_price" decimal(10,2) DEFAULT 0,
  "stock" integer NOT NULL DEFAULT 0
);

CREATE TABLE "product_images" (
  "product_id" integer,
  "media_id" integer,
  "is_primary" boolean DEFAULT false,
  PRIMARY KEY ("product_id", "media_id")
);

CREATE TABLE "customers" (
  "customer_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "store_id" integer NOT NULL,
  "customer_name" varchar NOT NULL,
  "customer_phone" varchar,
  "customer_address" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "orders" (
  "order_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "store_id" integer NOT NULL,
  "customer_id" integer NOT NULL,
  "created_by_user_id" integer NOT NULL,
  "order_date" date NOT NULL,
  "order_status" varchar NOT NULL,
  "total_amount" decimal(12,2),
  "notes" text
);

CREATE TABLE "order_items" (
  "order_item_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer NOT NULL,
  "product_id" integer,
  "variant_id" integer,
  "quantity" integer NOT NULL,
  "price_per_item" decimal(10,2) NOT NULL
);

CREATE TABLE "shipments" (
  "shipment_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer UNIQUE NOT NULL,
  "courier_name" varchar,
  "tracking_number" varchar,
  "shipping_cost" decimal(10,2),
  "shipped_date" date
);

COMMENT ON COLUMN "users"."role" IS '''owner'', ''administrator'', ''store_owner'', ''store_employee''';

COMMENT ON COLUMN "categories"."parent_category_id" IS 'Self-referencing for sub-categories';

COMMENT ON COLUMN "product_variants"."variant_name" IS 'e.g., "Ukuran"';

COMMENT ON COLUMN "product_variants"."variant_value" IS 'e.g., "L"';

COMMENT ON COLUMN "orders"."order_status" IS '''pending'', ''processing'', ''shipped'', ''completed'', ''cancelled''';

ALTER TABLE "user_profiles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE;

ALTER TABLE "stores" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("user_id") ON DELETE CASCADE;

ALTER TABLE "stores" ADD FOREIGN KEY ("store_id") REFERENCES "users" ("store_id") ON DELETE SET NULL;

ALTER TABLE "media" ADD FOREIGN KEY ("uploaded_by_user_id") REFERENCES "users" ("user_id") ON DELETE SET NULL;

ALTER TABLE "media" ADD FOREIGN KEY ("media_id") REFERENCES "user_profiles" ("avatar_media_id") ON DELETE SET NULL;

ALTER TABLE "media" ADD FOREIGN KEY ("media_id") REFERENCES "stores" ("logo_media_id") ON DELETE SET NULL;

ALTER TABLE "media" ADD FOREIGN KEY ("media_id") REFERENCES "store_layouts" ("head_favicon_media_id") ON DELETE SET NULL;

ALTER TABLE "media" ADD FOREIGN KEY ("media_id") REFERENCES "store_layouts" ("seo_og_image_media_id") ON DELETE SET NULL;

ALTER TABLE "store_layouts" ADD FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id") ON DELETE CASCADE;

ALTER TABLE "products" ADD FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id") ON DELETE CASCADE;

ALTER TABLE "categories" ADD FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id") ON DELETE CASCADE;

ALTER TABLE "customers" ADD FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id") ON DELETE CASCADE;

ALTER TABLE "categories" ADD FOREIGN KEY ("category_id") REFERENCES "products" ("category_id") ON DELETE SET NULL;

ALTER TABLE "categories" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("parent_category_id") ON DELETE SET NULL;

ALTER TABLE "product_variants" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") ON DELETE CASCADE;

ALTER TABLE "product_images" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") ON DELETE CASCADE;

ALTER TABLE "product_images" ADD FOREIGN KEY ("media_id") REFERENCES "media" ("media_id") ON DELETE CASCADE;

ALTER TABLE "orders" ADD FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id") ON DELETE CASCADE;

ALTER TABLE "orders" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("customer_id") ON DELETE CASCADE;

ALTER TABLE "orders" ADD FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("user_id") ON DELETE SET NULL;

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id") ON DELETE CASCADE;

ALTER TABLE "products" ADD FOREIGN KEY ("product_id") REFERENCES "order_items" ("product_id") ON DELETE SET NULL;

ALTER TABLE "product_variants" ADD FOREIGN KEY ("variant_id") REFERENCES "order_items" ("variant_id") ON DELETE SET NULL;

ALTER TABLE "shipments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id") ON DELETE CASCADE;
